// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC87Lw8BJtzQjhVBD-UdM7Dgyj3LlBSIag',
    appId: '1:751924395440:web:0f54f0379a7daf6baa2a75',
    messagingSenderId: '751924395440',
    projectId: 'notifications-1720f',
    authDomain: 'notifications-1720f.firebaseapp.com',
    storageBucket: 'notifications-1720f.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBLallyLgwxczi0wCkQsn7-GPQYsMjD2zE',
    appId: '1:751924395440:android:d114be3cf89ba378aa2a75',
    messagingSenderId: '751924395440',
    projectId: 'notifications-1720f',
    storageBucket: 'notifications-1720f.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBNfNexv4-pdU-srfplN3-ibXMBB6fyCV0',
    appId: '1:751924395440:ios:dc829d0364caa238aa2a75',
    messagingSenderId: '751924395440',
    projectId: 'notifications-1720f',
    storageBucket: 'notifications-1720f.appspot.com',
    iosBundleId: 'com.example.pushnotifications',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBNfNexv4-pdU-srfplN3-ibXMBB6fyCV0',
    appId: '1:751924395440:ios:dc829d0364caa238aa2a75',
    messagingSenderId: '751924395440',
    projectId: 'notifications-1720f',
    storageBucket: 'notifications-1720f.appspot.com',
    iosBundleId: 'com.example.pushnotifications',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC87Lw8BJtzQjhVBD-UdM7Dgyj3LlBSIag',
    appId: '1:751924395440:web:1529a508fa0315a9aa2a75',
    messagingSenderId: '751924395440',
    projectId: 'notifications-1720f',
    authDomain: 'notifications-1720f.firebaseapp.com',
    storageBucket: 'notifications-1720f.appspot.com',
  );
}
